---
layout: single
classes: wide
title: "우당탕탕 2"
categories:
  - 우당탕탕
last_modified_at: 2020-02-28T13:00:00+09:00
---
# 그놈의 Kernel Error
**FileNotFoundError: [Errno 2] No such file or directory: 'gophernotes': 'gophernotes'**

다행인건지 어쩐건지, 이러한 오류에 봉착한 사람은 나 뿐만이 아니었다. 참고한 링크는 https://github.com/gopherdata/gophernotes/issues/162 이다.

우선, 터미널에서 커널의 위치를 확인해보자.
```
$jupyter kernelspec list

Available kernels:
  gophernotes    /Users/seonwoolim/Library/Jupyter/kernels/gophernotes
  ir             /Users/seonwoolim/Library/Jupyter/kernels/ir
  python3        /Users/seonwoolim/anaconda3/share/jupyter/kernels/python3
```

고퍼노트 커널의 위치를 복사해놓고, 그 위치의 kernel.json 을 연다.

```
$sudo nano /Users/seonwoolim/Library/Jupyter/kernels/gophernotes/kernel.json
Password: #컴퓨터 비밀번호 입력 후 엔터

{
    "argv": [
        "gophernotes",
        "{connection_file}"
    ],
    "display_name": "Go",
    "language": "go",
    "name": "go"
}
```
"gophernotes" 라고 되어있는 부분을 복사해두었던 커널 경로로 바꾸고 저장한다. 그러고 나면 filenotfound 오류가 아닌 permission 오류가 난다!! ㅎㅎ 와 데다네

```
[E 11:40:57.709 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
        type=mtype))
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/Users/seonwoolim/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/Users/seonwoolim/Library/Jupyter/kernels/gophernotes'
```
